version: "3"
services:
  mongodb:
    image: mongo:4.2.3
    container_name: "mongodb"
    ports:
    - 27017:27017
  seguradoraapi:
    image: alexoshiro/seguradora-api:1.0.0
    ports:
    - 8080:8080
    environment:
    - MONGO_URI=mongodb://mongodb:27017
    links:
    - mongodb